url: https://github.com/robo-jordo
baseurl: /portfolio/

# Site settings
title: Jordan Haskel
email: jordhask@gmail.com.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: linkedin 
    url: 
  - title: github
    url: https://github.com/robo-jordo

# Postal address (add as many lines as necessary)
address:
  - line: 1596 Oak Avenue
  - line: APT 2
  - line: Evanston, IL, 60201

# Build settings
markdown: kramdown
permalink: pretty